#!/usr/bin/env bash
DARKFOREST_HOME=../darkforestGo
TORCH_HOME=../torch
TIME_LIMIT=1 # DEBUG
TIME_LIMIT=0 # UNLIMITED

# UPDATE PATH FOR LUA, TORCH
. $TORCH_HOME/install/bin/torch-activate

cd $DARKFOREST_HOME/cnnPlayerV2
th cnnPlayerMCTSV2.lua --num_gpu 1 --time_limit $TIME_LIMIT

